<a href="https://colab.research.google.com/github/routparam12/Python_qns/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# .npy ek single NumPy array ko save karta hai.

In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40])

# Save
np.save("data.npy", arr)

loaded_arr = np.load("data.npy")

print(loaded_arr)

[10 20 30 40]


# .npz — Multiple Arrays Store Karna

In [6]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

np.savez("dataset.npz", x=x, y=y)

load_data = np.load("dataset.npz")


print(load_data["x"])
print(load_data["y"])

[1 2 3]
[10 20 30]
