<a href="https://colab.research.google.com/github/routparam12/Python_qns/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import  numpy as np

#1D vector
s = np.array([1,2,5])
print(type(s))

#2D metrics
h = np.array([[14,8,0],[4,7,8]])
print(h)

#3D- tensor
j = np.array([[2,6,8],[4,7,9],[2,6,8]])
print(j)

<class 'numpy.ndarray'>
[[14  8  0]
 [ 4  7  8]]
[[2 6 8]
 [4 7 9]
 [2 6 8]]


In [13]:
#float data type
np.array([1,4,7,8,9],dtype=float)


#boolean data type
np.array([1,4,7,8,9],dtype=bool)

np.array([1,4,7,8,9],dtype=complex)

array([1.+0.j, 4.+0.j, 7.+0.j, 8.+0.j, 9.+0.j])

In [18]:
#np.arange
np.arange(1,9)
np.arange(1,9,2)


array([1, 3, 5, 7])

In [38]:
# with reshape
np.arange(1,9).reshape(4,2)
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [33]:
#np.ones an np.zeros
np.ones((3,4))
np.zeros((3,4))
np.random.random((3,6))

array([[0.1819918 , 0.04797238, 0.01207928, 0.26901797, 0.94544045,
        0.22964163],
       [0.69589583, 0.30833443, 0.16615092, 0.20602378, 0.34763924,
        0.98199532],
       [0.67270433, 0.44494288, 0.86800444, 0.71386434, 0.12248675,
        0.42099508]])

In [36]:
#np.linspace - linear distance main numbers create kar ke deta hai
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [35]:
#np.identity  -- diagonal axis have value others are 0
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
# ndim - number of dimensions
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1.ndim
a2.ndim
a3.ndim

3

In [45]:
#Shape - tells us the shape of array
a2.shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [47]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [52]:
# itemsize  -- the int64 takes 8 byte to store its value
a1.itemsize
print(a1.dtype)
a3.itemsize
a2.itemsize

int64


8

#Changing Datatype

In [53]:
#astype does a type caste for all the variables
a3.astype(np.int32)
a3.dtype

dtype('int64')

In [59]:
#Scalar  operations
a3**2
#a1 + 2


array([[[ 0,  1],
        [ 4,  9]],

       [[16, 25],
        [36, 49]]])

In [60]:
#relational operations
a2 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])