<a href="https://colab.research.google.com/github/routparam12/Python_qns/blob/main/Pytorch_Tensors01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import torch
print(torch.__version__)

2.11.0+cu128


In [21]:
if torch.cuda.is_available():
    print("cuda is available")
    print(torch.cuda.get_device_name(0))
else:
    print("cuda is not available")

cuda is available
Tesla T4


Creating a Tensor

In [22]:
#uning Empty
a = torch.empty(2,3)
# returns the value already existing in the empty space

In [23]:
#check type
type(a)

torch.Tensor

In [24]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [25]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [26]:
#using rand -- returns random values and those
torch.rand(2,3)

tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])

In [27]:
#use of seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

Tensor Shape

In [28]:
import torch
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [29]:
x.shape

torch.Size([2, 3])

Tensor DataType

In [30]:
#Find dataType
x.dtype

torch.int64

In [31]:
#assign dataType
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

Mathematical operations

In [32]:
#Addition
x + 2

# division
x / 2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [33]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])


In [34]:
#Addition
a + b

#power
a ** b

#mod
a % b

tensor([[0.2566, 0.2259, 0.1997],
        [0.1332, 0.0492, 0.0197]])

In [35]:
#sqrt
torch.sqrt(x)

tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])

In [36]:
k = torch.randint(size=(2,3), low = 0, high=10, dtype=torch.float32 )

In [37]:
#softmax
torch.softmax(k,dim=0)

tensor([[7.3106e-01, 9.5257e-01, 9.9966e-01],
        [2.6894e-01, 4.7426e-02, 3.3535e-04]])

In [38]:
#relu
torch.relu(k)

tensor([[7., 6., 9.],
        [6., 3., 1.]])

#Reshaping tensor

In [39]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [41]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
b = torch.rand(2,3,4)
b

tensor([[[0.1053, 0.2695, 0.3588, 0.1994],
         [0.5472, 0.0062, 0.9516, 0.0753],
         [0.8860, 0.5832, 0.3376, 0.8090]],

        [[0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464],
         [0.7890, 0.2814, 0.7886, 0.5895]]])

In [43]:
#permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [44]:
#unsqeeze
#image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [45]:
#sqeez
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

Numpy and torch

In [46]:
import numpy as np

In [47]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [48]:
b = a.numpy( )
b

array([1, 2, 3])

In [49]:
type(b)

numpy.ndarray

In [50]:
c = np.array([1,2,3])
c

array([1, 2, 3])

Example 2 : Calculate the value of x ? y = x*x, z = sin(y)

In [51]:
import math

def dz_dx(x):
  return 2 * x * math.cos(x**2)

dz_dx(2)

-2.6145744834544478

In [52]:
x = torch.tensor(3.0, requires_grad=True)

In [53]:
y = x ** 2

In [54]:
z = torch.sin(y)

In [55]:
x

tensor(3., requires_grad=True)

In [56]:
y

tensor(9., grad_fn=<PowBackward0>)

In [57]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [58]:
z.backward()

In [59]:
x.grad

tensor(-5.4668)

#Next we will calculate the \\

In [60]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [61]:
w = torch.tensor(1.0,requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [62]:
w

tensor(1., requires_grad=True)

In [63]:
b

tensor(0., requires_grad=True)

In [64]:
z = w*x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)