<a href="https://colab.research.google.com/github/routparam12/Python_qns/blob/main/Pytorch_Tensors01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.11.0+cu128


In [3]:
if torch.cuda.is_available():
    print("cuda is available")
    print(torch.cuda.get_device_name(0))
else:
    print("cuda is not available")

cuda is available
Tesla T4


Creating a Tensor

In [4]:
#uning Empty
a = torch.empty(2,3)
# returns the value already existing in the empty space

In [5]:
#check type
type(a)

torch.Tensor

In [6]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
#using rand -- returns random values and those
torch.rand(2,3)

tensor([[0.9402, 0.5272, 0.8785],
        [0.1514, 0.1964, 0.5539]])

In [9]:
#use of seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

Tensor Shape

In [13]:
import torch
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

Tensor DataType

In [15]:
#Find dataType
x.dtype

torch.int64

In [18]:
#assign dataType
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

Mathematical operations

In [20]:
#Addition
x + 2

# division
x / 2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [22]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])
tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])


In [25]:
#Addition
a + b

#power
a ** b

#mod
a % b

tensor([[5.5950e-02, 8.8459e-02, 2.6963e-01],
        [4.2636e-02, 2.9692e-01, 2.6345e-05]])

In [26]:
#sqrt
torch.sqrt(x)

tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])

In [31]:
k = torch.randint(size=(2,3), low = 0, high=10, dtype=torch.float32 )

In [32]:
#softmax
torch.softmax(x,dim=0)

tensor([[0.0474, 0.0474, 0.0474],
        [0.9526, 0.9526, 0.9526]])

In [33]:
#relu
torch.relu(k)

tensor([[9., 6., 2.],
        [0., 6., 2.]])

#Reshaping tensor

In [34]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [36]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
b = torch.rand(2,3,4)
b

tensor([[[0.7104, 0.9464, 0.7890, 0.2814],
         [0.7886, 0.5895, 0.7539, 0.1952],
         [0.0050, 0.3068, 0.1165, 0.9103]],

        [[0.6440, 0.7071, 0.6581, 0.4913],
         [0.8913, 0.1447, 0.5315, 0.1587],
         [0.6542, 0.3278, 0.6532, 0.3958]]])

In [38]:
#permute
b.permute(2,0,1).shape

tensor([[[0.7104, 0.7886, 0.0050],
         [0.6440, 0.8913, 0.6542]],

        [[0.9464, 0.5895, 0.3068],
         [0.7071, 0.1447, 0.3278]],

        [[0.7890, 0.7539, 0.1165],
         [0.6581, 0.5315, 0.6532]],

        [[0.2814, 0.1952, 0.9103],
         [0.4913, 0.1587, 0.3958]]])

In [40]:
#unsqeeze
#image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [44]:
#sqeez
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

Numpy and torch

In [45]:
import numpy as np

In [46]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [50]:
b = a.numpy( )
b

array([1, 2, 3])

In [51]:
type(b)

numpy.ndarray

In [52]:
c = np.array([1,2,3])
c

array([1, 2, 3])